import type { D1Database } from '@cloudflare/workers-types';
import { publicMediaSrc } from './media-management';
export const retailFields = {
 retail_summary:'Retail summary',retail_square_feet:'Retail square feet',retail_floor:'Floor / location',storefront_frontage:'Storefront frontage',ceiling_height:'Ceiling height',corner_location:'Corner location',street_exposure:'Street exposure',basement_storage:'Lower level / storage',venting:'Venting',gas_available:'Gas',electrical_notes:'Electrical capacity',accessibility_notes:'Accessibility',loading_notes:'Loading / delivery',signage_notes:'Signage',approved_uses:'Approved uses',transit_notes:'Nearby transit',retail_availability_status:'Availability',retail_contact_notes:'Internal contact notes',tenant_website:'Tenant website',retail_brochure_asset_id:'Brochure asset',retail_floorplan_asset_id:'Floor-plan asset'
} as const;
export type RetailField=keyof typeof retailFields;
export type RetailProfile=Record<RetailField,string|number|null>&{published_fields_json:string;provenance_json:string};
export const publicFactFields=(Object.keys(retailFields) as RetailField[]).filter(key=>!['retail_contact_notes','retail_brochure_asset_id','retail_floorplan_asset_id','retail_summary','tenant_website','retail_availability_status'].includes(key));
export async function retailProfile(db:D1Database,id:string){return db.prepare('SELECT * FROM retail_profiles WHERE building_id=?').bind(id).first<RetailProfile>();}
export function approvedRetailFacts(row:RetailProfile|null){if(!row)return [];let published:string[]=[],provenance:Record<string,string>={};try{published=JSON.parse(row.published_fields_json);provenance=JSON.parse(row.provenance_json)}catch{}return publicFactFields.filter(key=>published.includes(key)&&['verified','client_supplied'].includes(provenance[key])&&row[key]!==null&&row[key]!=='').map(key=>({label:retailFields[key],value:String(row[key])}));}
export function approvedRetailValue(row:RetailProfile|null,key:RetailField){if(!row)return null;try{const fields=JSON.parse(row.published_fields_json) as string[];const provenance=JSON.parse(row.provenance_json) as Record<string,string>;return fields.includes(key)&&['verified','client_supplied'].includes(provenance[key])&&row[key]!==null&&row[key]!==''?String(row[key]):null;}catch{return null;}}
export type RetailImage={src:string;alt:string;kind:string};
export async function approvedRetailGallery(db:D1Database,id:string):Promise<RetailImage[]>{const rows=(await db.prepare("SELECT a.id,a.storage_key,COALESCE(NULLIF(m.alt_text,''),a.alt_text) AS alt,r.kind FROM retail_media_approvals r JOIN media_assets a ON a.id=r.asset_id AND a.visibility='public' AND a.file_type LIKE 'image/%' JOIN media_assignments m ON m.asset_id=a.id AND m.building_id=r.building_id JOIN media_publications p ON p.assignment_id=m.id AND p.published=1 WHERE r.building_id=? AND r.published=1 ORDER BY r.order_index,a.id").bind(id).all<{id:string;storage_key:string;alt:string|null;kind:string}>()).results;return rows.map(row=>({src:publicMediaSrc({id:row.id,storage_key:row.storage_key} as Parameters<typeof publicMediaSrc>[0]),alt:row.alt||`Approved ${row.kind} photograph`,kind:row.kind}));}
