#:schema node_modules/wrangler/config-schema.json
name = "teams-management-worker"

# Development environment - binds to live D1 created above
[[d1_databases]]
binding = "DB"
database_name = "teams-database-dev"
database_id = "2d04fbea-8af6-4d6d-b5bf-cf758666d55e"

[vars]
NEXT_PUBLIC_ENVIRONMENT = "development"
