export const runtime = 'edge';
import { PageShowcase } from '@/components/page-showcase';
import Link from 'next/link';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { ContactDetails } from '@/components/contact-details';

export default async function AboutPage() {
  return <><Header /><main><section className="texture-graphite bg-teams-charcoal text-white py-16 sm:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="h-px w-14 bg-white/50 mb-6" /><p className="uppercase tracking-[.2em] text-xs text-slate-200 mb-4">Teams Management</p><h1 className="mb-5 text-4xl sm:text-6xl font-serif">About Us</h1><p className="max-w-2xl text-lg text-slate-200">The Property Steward: a considered approach to presenting and caring for a New York property portfolio.</p></div></section><section className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6 grid md:grid-cols-2 gap-12"><div><h2 className="mb-5 text-3xl font-serif text-teams-ink">Our approach</h2><p className="text-slate-700 leading-relaxed">Teams Management is building a property-first experience around clear locations, reviewed building information, and direct communication. Details are published only after verification.</p></div><div className="border-l-2 border-slate-300 pl-7"><h2 className="mb-5 text-3xl font-serif text-teams-ink">New York portfolio</h2><p className="text-slate-700 leading-relaxed mb-6">The Phase 1 portfolio includes supplied addresses in Flushing, the Bronx, and Manhattan. Individual building stories and imagery are being prepared for publication.</p><Link href="/properties" className="inline-flex bg-teams-gold px-6 py-3 font-semibold text-teams-ink hover:bg-teams-gold-highlight">Explore properties</Link></div></div><div className="mx-auto max-w-5xl px-4 sm:px-6 mt-14 border-t border-slate-200 pt-8"><h2 className="mb-5 text-2xl font-serif text-teams-ink">Company contact</h2><ContactDetails /></div></section><PageShowcase page="about" variant="offset"/></main><Footer /></>;
}
