'use client';
import {useEffect,useState} from 'react';
type Unit={id:string;building_id:string;building_name:string;unit_identifier:string;floor_number:number;layout_id:string|null;status:string};type Building={id:string;name:string};
const statuses=['available_internal','occupied','under_construction','maintenance'];
export default function UnitsPage(){const [rows,setRows]=useState<Unit[]>([]),[buildings,setBuildings]=useState<Building[]>([]),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState({building_id:'',unit_identifier:'',floor_number:1,layout_id:'',status:'available_internal'});
 async function load(search=''){try{const [u,b]=await Promise.all([fetch('/api/admin/units?q='+encodeURIComponent(search),{cache:'no-store'}),fetch('/api/admin/buildings',{cache:'no-store'})]);if(!u.ok||!b.ok)throw new Error('Unable to load units');setRows(await u.json());setBuildings(await b.json());}catch(e){setError(String(e));}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch(editing?`/api/admin/units/${editing}`:'/api/admin/units',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,layout_id:form.layout_id||null})});if(!r.ok)throw new Error('Save failed; check building and layout IDs');setEditing(null);setForm({building_id:'',unit_identifier:'',floor_number:1,layout_id:'',status:'available_internal'});await load(q);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-semibold">Internal units</h1><p className="mt-2">Unit records are private and never shown in the public portfolio.</p><form className="my-5 flex gap-2" onSubmit={e=>{e.preventDefault();void load(q);}}><label className="sr-only" htmlFor="unit-search">Search units</label><input id="unit-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Building or unit" className="rounded border p-2"/><button className="rounded border px-3">Search</button></form>{error&&<p role="alert" className="text-red-700">{error}</p>}<ul className="space-y-2">{rows.map(row=><li key={row.id} className="rounded border p-3">{row.building_name} · {row.unit_identifier} · Floor {row.floor_number} · {row.status} <button className="ml-3 underline" onClick={()=>{setEditing(row.id);setForm({building_id:row.building_id,unit_identifier:row.unit_identifier,floor_number:row.floor_number,layout_id:row.layout_id||'',status:row.status});}}>Edit</button></li>)}</ul>{rows.length===0&&<p>No units found.</p>}<form onSubmit={save} className="mt-8 grid max-w-lg gap-3"><h2 className="text-xl font-semibold">{editing?'Edit unit':'Create unit'}</h2><label>Building<select required className="block w-full rounded border p-2" value={form.building_id} onChange={e=>setForm({...form,building_id:e.target.value})}><option value="">Select building</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Unit identifier<input required className="block w-full rounded border p-2" value={form.unit_identifier} onChange={e=>setForm({...form,unit_identifier:e.target.value})}/></label><label>Floor<input required type="number" min={-10} max={300} className="block w-full rounded border p-2" value={form.floor_number} onChange={e=>setForm({...form,floor_number:Number(e.target.value)})}/></label><label>Layout ID (optional)<input className="block w-full rounded border p-2" value={form.layout_id} onChange={e=>setForm({...form,layout_id:e.target.value})}/></label><label>Status<select className="block w-full rounded border p-2" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><div className="flex gap-3"><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{busy?'Saving…':'Save'}</button><button type="button" className="rounded border px-4" onClick={()=>setEditing(null)}>Cancel</button></div></form></main>}
