-- Add only the eleven client-supplied properties absent from the initial D1 seed.
-- Keep them draft until descriptions, locations and media are approved.
-- Do not overwrite the four existing real records or guess ZIP codes.
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-173-e-91st-st', '173 E 91st St.', '173-e-91st-st', NULL, '{"street":"173 E 91st St.","city":"New York","state":"NY","zip":"","neighborhood":"Upper East Side"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-1626-2nd-ave', '1626 2nd Ave.', '1626-2nd-ave', NULL, '{"street":"1626 2nd Ave.","city":"New York","state":"NY","zip":"","neighborhood":"East Harlem"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-225-e-83rd-st', '225 E 83rd St.', '225-e-83rd-st', NULL, '{"street":"225 E 83rd St.","city":"New York","state":"NY","zip":"","neighborhood":"Upper East Side"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-171-e-74th-st', '171 E 74th St.', '171-e-74th-st', NULL, '{"street":"171 E 74th St.","city":"New York","state":"NY","zip":"","neighborhood":"Upper East Side"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-1374-1st-ave', '1374 1st Ave.', '1374-1st-ave', NULL, '{"street":"1374 1st Ave.","city":"New York","state":"NY","zip":"","neighborhood":"Upper East Side"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-1365-1st-ave', '1365 1st Ave.', '1365-1st-ave', NULL, '{"street":"1365 1st Ave.","city":"New York","state":"NY","zip":"","neighborhood":"Upper East Side"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-41-w-46th-st', '41 W 46th St.', '41-w-46th-st', NULL, '{"street":"41 W 46th St.","city":"New York","state":"NY","zip":"","neighborhood":"Midtown"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-349-351-w-46th-st', '349-351 W 46th St.', '349-351-w-46th-st', NULL, '{"street":"349-351 W 46th St.","city":"New York","state":"NY","zip":"","neighborhood":"Midtown"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-307-w-39th-st', '307 W 39th St.', '307-w-39th-st', NULL, '{"street":"307 W 39th St.","city":"New York","state":"NY","zip":"","neighborhood":"Chelsea"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-235-w-18th-st', '235 W 18th St.', '235-w-18th-st', NULL, '{"street":"235 W 18th St.","city":"New York","state":"NY","zip":"","neighborhood":"West Village"}', '[]', '[]', 'draft');
INSERT OR IGNORE INTO buildings (id, name, slug, description_public, address_json, amenities_public, gallery, publication_state) VALUES ('real-61-gold-st', '61 Gold St.', '61-gold-st', NULL, '{"street":"61 Gold St.","city":"New York","state":"NY","zip":"","neighborhood":"Financial District"}', '[]', '[]', 'draft');
UPDATE buildings SET publication_state = 'draft' WHERE slug = 'test-building' AND id = 'build-005';
