-- Canonical Phase 1 portfolio. Supplied address and portfolio membership are the only verified facts.
-- Idempotent; never overwrites editorial work or publication decisions.
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('build-001','42-70 156th St','42-70-156th-st-flushing','{"street":"42-70 156th St","city":"Flushing","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('build-002','3425 East Tremont Ave','3425-east-tremont-bronx','{"street":"3425 East Tremont Ave","city":"Bronx","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('build-003','166-170 E 118th St','166-170-e-118th-st','{"street":"166-170 E 118th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('build-004','71 E 110th St','71-e-110th-st','{"street":"71 E 110th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-173-e-91st-st','173 E 91st St','173-e-91st-st','{"street":"173 E 91st St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-1626-2nd-ave','1626 2nd Ave','1626-2nd-ave','{"street":"1626 2nd Ave","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-225-e-83rd-st','225 E 83rd St','225-e-83rd-st','{"street":"225 E 83rd St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-171-e-74th-st','171 E 74th St','171-e-74th-st','{"street":"171 E 74th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-1374-1st-ave','1374 1st Ave','1374-1st-ave','{"street":"1374 1st Ave","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-1365-1st-ave','1365 1st Ave','1365-1st-ave','{"street":"1365 1st Ave","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-41-w-46th-st','41 W 46th St','41-w-46th-st','{"street":"41 W 46th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-349-351-w-46th-st','349-351 W 46th St','349-351-w-46th-st','{"street":"349-351 W 46th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-307-w-39th-st','307 W 39th St','307-w-39th-st','{"street":"307 W 39th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-235-w-18th-st','235 W 18th St','235-w-18th-st','{"street":"235 W 18th St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
INSERT OR IGNORE INTO buildings (id,name,slug,address_json,description_public,amenities_public,gallery,publication_state) VALUES ('real-61-gold-st','61 Gold St','61-gold-st','{"street":"61 Gold St","city":"New York","state":"NY"}',NULL,'[]','[]','draft');
