-- Superseded historical draft. Do not apply: it contained unverified property details.
-- Use schema.sql, seed-data.sql, and canonical-portfolio-phase1.sql instead.
-- Historical contents remain available in Git history for audit.
