'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
type Building={id:string;name:string;slug:string;address_json:string;publication_state:string};
const blank={name:'',slug:'',street:'',city:'',state:'',zip:'',neighborhood:''};
export default function BuildingsPage(){
 const [rows,setRows]=useState<Building[]>([]),[q,setQ]=useState(''),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(search=''){try{const r=await fetch('/api/admin/buildings?q='+encodeURIComponent(search),{cache:'no-store'});if(!r.ok)throw new Error('Unable to load buildings');setRows(await r.json());}catch(e){setError(String(e));}}
 useEffect(()=>{void load();},[]);
 function edit(row:Building){const address=JSON.parse(row.address_json);setForm({name:row.name,slug:row.slug,street:address.street||'',city:address.city||'',state:address.state||'',zip:address.zip||'',neighborhood:address.neighborhood||''});setEditing(row.id);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch(editing?`/api/admin/buildings/${editing}`:'/api/admin/buildings',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,...(!editing?{slug:form.slug}:{}),address:{street:form.street,city:form.city,state:form.state,zip:form.zip,neighborhood:form.neighborhood}})});if(!r.ok)throw new Error('Save failed; check required fields or duplicate slug.');setForm(blank);setEditing(null);await load(q);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function setState(row:Building,state:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/admin/buildings/${row.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({publication_state:state})});if(!r.ok)throw new Error('Status change failed');await load(q);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-semibold">Buildings</h1><form className="my-5 flex gap-2" onSubmit={e=>{e.preventDefault();void load(q);}}><label className="sr-only" htmlFor="building-search">Search buildings</label><input id="building-search" className="rounded border p-2" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search buildings"/><button className="rounded border px-3">Search</button></form>{error&&<p role="alert" className="text-red-700">{error}</p>}<ul className="space-y-3">{rows.map(row=><li key={row.id} className="rounded border p-3"><strong>{row.name}</strong> · {row.publication_state}<div className="mt-2 flex flex-wrap gap-2"><Link href={`/admin/buildings/${row.id}/preview`} className="underline">Preview</Link><button onClick={()=>edit(row)} className="underline">Edit</button>{['draft','internal_review','archived'].filter(s=>s!==row.publication_state).map(s=><button key={s} disabled={busy} onClick={()=>void setState(row,s)} className="underline disabled:opacity-50">{s==='draft'?'Unpublish':s==='internal_review'?'Mark for review':'Archive'}</button>)}</div></li>)}</ul>{rows.length===0&&<p>No buildings found.</p>}<p className="mt-4 text-sm text-slate-600">Publishing is paused until property copy and media are approved. Archived QA records are excluded from this list.</p><form onSubmit={save} className="mt-8 grid max-w-lg gap-3"><h2 className="text-xl font-semibold">{editing?'Edit building':'Create draft building'}</h2>{Object.keys(blank).map(key=><label key={key} className="grid gap-1 capitalize">{key}<input required={['name','slug','street','city','state'].includes(key)&&(!editing||key!=='slug')} disabled={editing!==null&&key==='slug'} className="rounded border p-2" value={form[key as keyof typeof blank]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<div className="flex gap-3"><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{busy?'Saving…':'Save'}</button><button type="button" onClick={()=>{setForm(blank);setEditing(null);}} className="rounded border px-4">Cancel</button></div></form></main>;
}
