import Link from 'next/link';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { previewPortfolioEnabled } from '@/lib/preview-portfolio';

const faq = [
  { question: 'When is rent due?', answer: <>Rent is due on the first day of each month unless your lease provides otherwise. Where permitted by your lease and applicable law, a late fee may apply only after the five-day grace period. The fee cannot exceed $50 or 5% of your monthly rent, whichever is less.<br /><br />Make checks payable to the building entity identified in your lease. Mailed payments should be sent to Teams Management, 1374 First Avenue, Suite 1A, New York, NY 10021. Contact the office with payment questions.</> },
  { question: 'What if I don’t receive my monthly rent bill?', answer: <>Rent bills are provided for convenience. Please pay the rent due under your lease on time even if a bill does not arrive. If you are unsure of the amount or notice a billing discrepancy, contact the office promptly.</> },
  { question: 'What should I do if I lose my keys or have a lock problem?', answer: <>You will receive keys when you move in. Contact management if you lose a key, need a replacement, or have a broken lock. We will explain the appropriate replacement or locksmith procedure and any lawful charges. Report damaged building-entry or apartment locks promptly. If you change an apartment lock, provide management with a duplicate key as required by law. <a href="https://www.nyc.gov/site/hpd/services-and-information/tenants-rights-and-responsibilities.page">NYC HPD</a></> },
  { question: 'Can I install an air conditioner?', answer: <>Contact management before installation to confirm the building’s requirements, including professional installation and insurance documentation. The unit must be safely secured and installed according to manufacturer instructions and applicable rules.<br /><br />Never block a fire-escape window or another exit. Keep fire escapes, hallways and other exit routes clear. <a href="https://home4.nyc.gov/site/buildings/property-or-business-owner/installing-air-conditioning-units.page">NYC Buildings</a></> },
  { question: 'Can I decorate my apartment?', answer: <>Yes. Check your lease and obtain written approval before painting or making alterations that require permission. At move-out, remove your belongings and leave the apartment clean. You may be responsible for damage beyond ordinary wear and tear or for restoring unauthorized alterations. Security-deposit deductions must comply with applicable law.</> },
  { question: 'Who maintains smoke and carbon monoxide alarms?', answer: <>The owner provides and installs required alarms and replaces them when their useful life expires. Residents must maintain and test alarms, replace replaceable batteries according to device instructions, and never disable or remove them. Contact management promptly about a missing or malfunctioning alarm.<br /><br />If an alarm indicates a possible fire or carbon monoxide emergency, leave the affected area and call 911. <a href="https://www.nyc.gov/site/hpd/services-and-information/detectors.page">NYC HPD detector guidance</a></> },
  { question: 'What utilities are included?', answer: <>Heat and hot water are included unless your apartment’s lease or applicable requirements provide otherwise. Check your lease for responsibility for electricity, cooking gas, internet and other services. Contact management if you need clarification before opening utility accounts.</> },
  { question: 'Do I need window guards?', answer: <>In covered NYC buildings, approved window guards are required when a child age 10 or younger lives in the apartment. You may also request guards even if no child lives there.<br /><br />Management arranges installation in eligible windows; fire-escape windows have different requirements. Complete the annual window-guard notice and report household changes promptly. Any permitted charge depends on your apartment’s status; rent-stabilized or rent-controlled apartments have a maximum charge of $10 per guard. <a href="https://home4.nyc.gov/site/doh/health/health-topics/window-guards.page">NYC Health</a></> },
  { question: 'Do you allow pets?', answer: <>Contact management before bringing a pet into the apartment to confirm the policy for your building and lease, including any size or insurance requirements. Residents must prevent excessive noise and unsafe behavior and clean up after their animals. Service and emotional-support animals are handled through the reasonable-accommodation process rather than ordinary pet restrictions. Contact management to request an accommodation. <a href="https://www.nyc.gov/site/animalwelfare/resources/service-and-emotional-support-animals.page">NYC assistance-animal guidance</a></> },
  { question: 'Where should I dispose of garbage?', answer: <>Use your building’s designated disposal areas and labeled containers. Separate trash, recyclables and compostable material, including food scraps and food-soiled paper, according to NYC rules. Keep corridors and exits clear. Contact management before disposing of bulky items, electronics or hazardous materials. <a href="https://www.nyc.gov/site/dsny/collection/residents/curbside-composting.page">NYC Sanitation</a></> },
  { question: 'Can I renew my lease?', answer: <>Contact management about renewal options before your lease expires. Renewal rights and notice requirements depend on your apartment’s status and applicable law.<br /><br />For NYC rent-stabilized apartments, renewal offers generally must be delivered 90–150 days before expiration, with 60 days to respond. Other apartments may have protections under Good Cause Eviction and applicable notice rules. <a href="https://hcr.ny.gov/leases">NYS HCR</a>, <a href="https://www.nyc.gov/site/hpd/services-and-information/good-cause-eviction.page">NYC Good Cause guidance</a><br /><br />If you plan to move, give written notice consistent with your lease and applicable law. Management will coordinate inspections and reasonable access for showings, with appropriate notice.</> },
  { question: 'Can I end my lease early?', answer: <>Contact management as soon as possible to discuss your circumstances and available options. Moving out does not automatically end your lease obligations, but lawful early-termination rights may apply. New York law also requires residential landlords to take reasonable, good-faith steps to re-rent an apartment and reduce losses. Obtain any agreed release in writing. <a href="https://www.nysenate.gov/legislation/laws/RPP/227-E">NY law</a></> },
  { question: 'When will my security deposit be returned?', answer: <>Provide your forwarding address and return all keys when you move out. Deposits are subject only to lawful deductions, such as unpaid rent or damage beyond ordinary wear and tear.<br /><br />For apartments that are not rent-regulated, the remaining deposit and any itemized deductions generally must be provided within 14 days after you vacate. Rent-regulated apartments follow different return requirements. Ask management about your applicable deadline and any pre-move-out inspection rights. Do not treat the deposit as your last month’s rent without a written agreement. <a href="https://ag.ny.gov/publications/residential-tenants-rights-guide">NY Attorney General</a>, <a href="https://www.nysenate.gov/legislation/laws/GOB/7-108">NY security-deposit law</a></> },
];

export default function RentWithUsPage() {
  return <><Header /><main>
    <section className="bg-teams-charcoal text-white py-16 sm:py-20"><div className="max-w-5xl mx-auto px-4 sm:px-6"><div className="h-px w-14 bg-white/50 mb-6" /><p className="uppercase tracking-[.2em] text-xs text-slate-200 mb-4">A place to begin</p><h1 className="text-4xl sm:text-6xl font-serif mb-6">Rent with Us</h1><p className="max-w-2xl text-lg text-slate-200 leading-relaxed">Explore Teams Management properties and start a conversation about the location that interests you.</p></div></section>
    <section className="py-16 sm:py-20 bg-white"><div className="max-w-5xl mx-auto px-4 sm:px-6 grid md:grid-cols-2 gap-12"><div><h2 className="text-3xl font-serif text-teams-ink mb-5">Find your starting point</h2><p className="text-slate-700 leading-relaxed mb-7">Browse our published property profiles for verified building information. The portfolio is not an availability or apartment listings feed.</p><Link href="/properties" className="inline-flex bg-teams-gold px-6 py-3 font-semibold text-teams-ink hover:bg-teams-gold-highlight">Explore properties</Link></div><div className="border-l-2 border-slate-300 pl-7"><h2 className="text-3xl font-serif text-teams-ink mb-5">Ask about a property</h2><p className="text-slate-700 leading-relaxed mb-7">For a rental question, include the property address and what you would like to know. Availability, pricing, applications, and requirements are confirmed directly when information is available.</p><Link href="/contact" className="inline-flex border border-slate-300 px-6 py-3 text-teams-ink hover:bg-slate-50">Contact Teams</Link></div></div></section>
    {previewPortfolioEnabled && <section className="bg-stone-100 py-12"><div className="max-w-5xl mx-auto px-4 sm:px-6"><p className="uppercase tracking-[.2em] text-xs text-teams-secondary">Application preview</p><h2 className="text-3xl font-serif text-teams-ink mt-2 mb-3">Explore the rental application</h2><p className="text-teams-secondary max-w-2xl">The online form is being reviewed. You can explore its questions, but cannot submit or save answers yet.</p><div className="flex flex-wrap gap-3"><Link href="/rent-with-us/apply" className="inline-flex bg-teams-gold px-6 py-3 font-semibold text-teams-ink">Preview online form</Link><a href="/Teams_Management_Rental_Application_Fillable.pdf" download className="inline-flex border border-slate-400 px-6 py-3 font-semibold text-teams-ink">Download fillable PDF</a></div></div></section>}
    <section aria-labelledby="rent-faq-heading" className="bg-slate-50 py-16 sm:py-20"><div className="max-w-4xl mx-auto px-4 sm:px-6"><p className="uppercase tracking-[.2em] text-xs text-teams-secondary mb-3">Resident information</p><h2 id="rent-faq-heading" className="text-3xl sm:text-4xl font-serif text-teams-ink mb-4">Frequently Asked Questions</h2><p className="text-teams-secondary leading-relaxed mb-9">Your lease and applicable law govern where they differ from this general guidance.</p><div className="divide-y divide-slate-100 border-y border-slate-100">{faq.map(({ question, answer }) => <details key={question} className="group"><summary className="cursor-pointer list-none py-5 pr-8 text-lg font-semibold text-teams-ink marker:content-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teams-gold relative">{question}<span aria-hidden="true" className="absolute right-1 top-5 text-teams-secondary group-open:rotate-45 transition-transform">+</span></summary><div className="pb-6 pr-4 text-teams-secondary leading-relaxed [&_a]:underline [&_a]:underline-offset-4 [&_a]:decoration-teams-gold [&_a:hover]:text-teams-ink [&_a:focus-visible]:outline [&_a:focus-visible]:outline-2 [&_a:focus-visible]:outline-teams-gold">{answer}</div></details>)}</div></div></section>
  </main><Footer /></>;
}
